apiVersion: apps/v1
kind: Deployment
metadata:
  name: kandula-prod
  labels:
    app: backend
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      env: prod
  template:
    metadata:
      labels:
        app: backend
        env: prod
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: kalandula   
      containers:
      - name: kandula
        image: devmozes/kandula:latest
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
      # nodeSelector:
      #   app: kandula