apiVersion: apps/v1
kind: Deployment
metadata:
  name: kandula-prod
  labels:
    app: backend
    env: prod
    ver: "1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      env: prod
      ver: "1"
  template:
    metadata:
      labels:
        app: backend
        env: prod
        ver: "1"
    spec:
      containers:
      - name: kandula
        image: devmozes/kandula:latest
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP