apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
    env: prod
    ver: "1"
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30037
      protocol: TCP
    - name: http
      port: 9100
      targetPort: 9222
      nodePort: 30037
      protocol: TCP
