# Create a pod and expose port 8080
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    app: backend
spec:
  containers:
    - image: devmozes/kandula:latest
      name: kuard
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
