filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/auth.log
filebeat.modules:
  - module: system
    syslog:
      enabled: false
    auth:
      enabled: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.settings:
  index.number_of_shards: 1
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
output.elasticsearch:
# need to change to connet with counsul
  hosts: [ "Elasticsearch.service.opsschool.consul:9200" ]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
## OR
#output.logstash:
#  hosts: [ "127.0.0.1:5044" ]