---
- name: copy consul template
  template:
    dest: /home/ubuntu/consul-server.sh
    src: consul-server.j2
    mode: '0755'

- name: run script
  command: /home/ubuntu/consul-server.sh


# - name: get the machine private ip
#   shell:
#     cmd: curl http://169.254.169.254/latest/meta-data/local-ipv4
#   register: private_ip

# - set_fact:
#     private_ip: "{{ private_ip.stdout }}"

# - name: Install unzip and dnsmask
#   apt:
#     pkg:
#     - unzip
#     - dnsmask
#     update_cache: yes

# - name: Copy dnsmask conf file
#   ansible.builtin.copy:
#     src: 10-consul
#     dest: /etc/dnsmasq.d/
#     force: yes
#     owner: root
#     group: root
#     mode: '0644'
#   notify: "restart dnsmask service"

# - name: Copy resolved.conf file
#   ansible.builtin.copy:
#     src: resolved.conf
#     dest: /etc/systemd/
#     force: yes
#     owner: root
#     group: root
#     mode: '0644'
#   notify: "restart resolved service"

# - name: Download consul
#   get_url:
#     url: "https://releases.hashicorp.com/consul/{{ CONSUL_VERSION }}/consul_{{ CONSUL_VERSION }}_linux_amd64.zip"
#     dest: /tmp/consul.zip
#     # mode: '0440'